TKRBASE = {}
TKRBASE.Admin = {}
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- LIBS du serveur (vitale au fonctionnement du gamemode)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
include("libraries/resp/responsive.lua")
include("libraries/resp/panel.lua")
include("libraries/resp/materials.lua")
include("libraries/resp/anims.lua")
include("libraries/vgui/config.lua")
include("libraries/vgui/debug.lua")
include("libraries/vgui/base/frame.lua")
include("libraries/vgui/base/panel.lua")
include("libraries/vgui/base/label.lua")
include("libraries/vgui/inputs/button.lua")
include("libraries/vgui/inputs/textentry.lua")
include("libraries/vgui/inputs/checkbox.lua")
include("libraries/vgui/inputs/combobox.lua")
include("libraries/vgui/inputs/numslider.lua")
include("libraries/vgui/inputs/numwang.lua")
include("libraries/vgui/layout/scrollpanel.lua")
include("libraries/vgui/layout/iconlayout.lua")
include("libraries/vgui/layout/listlayout.lua")
include("libraries/vgui/layout/propertysheet.lua")
include("libraries/vgui/layout/collapsiblecategory.lua")
include("libraries/vgui/display/image.lua")
include("libraries/vgui/display/imagebutton.lua")
include("libraries/vgui/display/modelpanel.lua")
include("libraries/vgui/display/progress.lua")
include("libraries/vgui/display/colormixer.lua")
include("libraries/vgui/utility/notify.lua")
include("libraries/vgui/utility/listview.lua")
include("libraries/vgui/utility/tree.lua")
include("libraries/debug/config.lua")
include("libraries/debug/utils.lua")
include("libraries/anims/anims.lua")
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- MODULES Utilitaire (utilisation global)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
include("utils/pvar/cl_pvar.lua")
include("utils/pgroup/sh_groups.lua")
include("utils/pgroup/sh_config.lua")
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- MODULES Principaux (utilisation direct)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
include("modules/admin/vgui/cl_left.lua")
include("modules/admin/vgui/cl_logs.lua")
include("modules/admin/vgui/cl_player.lua")
include("modules/admin/vgui/cl_warns.lua")
include("modules/thirdperson/cl_thirdperson.lua")
include("modules/thirdperson/cl_thirdperson_ui.lua")
include("modules/logs/cl_logs_ui.lua")
include("modules/warns/cl_warns_ui.lua")
include("modules/contextmenu/cl_contextmenu.lua")